In [3]:
import numpy as np

In [7]:
#1
print(np.version.version, np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [9]:
#2 np.info(lafonction)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [10]:
#Array a
a = np.arange(1,10)
print(a)

#utiliser np.array(a) pour faire une copie sans modifer l'array de base

[1 2 3 4 5 6 7 8 9]


In [12]:
#3
n = True

for i in a:
    if i < 0:
        n = False
        break
    else:
        n = True
print(n)

True


In [22]:
#3 Utilisation de np.all en considérant que i=0 false, true si >0

print(np.all(a))

True


In [15]:
#4
i = int(input("Numéro de l'élément"))

if a[i] != 0:
    print("L'élément d'indice", i,"qui vaut",a[i], "n'est pas égal à 0")

L'élément d'indice 3 qui vaut 4 n'est pas égal à 0


In [23]:
#4 test wether any of the elemnts of a given array is non-zero

print(np.any(a))


True


In [32]:
#5 utilisation de np.Inf
#isinf(a) : Shows which elements are positive or negative infinity
#isposinf(a) : Shows which elements are positive infinity
#isneginf(a) : Shows which elements are negative infinity
#isnan(a) : Shows which elements are Not a Number
#isfinite(a) : Shows which elements are finite (not one of Not a Number, positive infinity and negative infinity)
a = np.array([1, 0, np.nan, np.inf])

i = int(input("Indice de l'élément"))

if np.isfinite(a[i]):
    print(a[i], "est fini")
else:
    print(a[i], "est soit infini soit nan")

In [26]:
#5
 
print(np.isfinite(a))

[ True  True False False]


In [40]:
#6

print(np.isinf(a))

[False False False  True]


In [ ]:
#6

print(np.isinf(a))

In [28]:
#7

print(np.isnan(a))

[False False  True False]


In [29]:
#8

a = np.array([i+1j, 1+0j, 4.5, 3, 2 , 2j])
print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar(3.1)) #valeur 3.1
print(np.isscalar([3.1])) #tableau indice 3.1

[ True False False False False  True]
[False  True  True  True  True False]
True
False


In [35]:
#9 utiliser np.allclose, compare avec une tolérance défini dans numpy
#si utilisation de np.nan, nécessaire equal_nan=True (exemple :  np.allclose([1.0, np.nan],[1.0, np.nan], equal_nan=True))

print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8],[1.00001e10,1e-9]))
print(np.allclose([1.0, np.nan],[1.0, np.nan]))
print(np.allclose([1.0, np.nan],[1.0, np.nan], equal_nan=True))

False
True
False
True


In [36]:
#10
x =np.array([3,5])
y = np.array([2,5])
print(x)
print(y)
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[3 5]
[2 5]
[ True False]
[ True  True]
[False False]
[False  True]


In [38]:
#11
x = np.array([72,79,85,90,150,-135,120,-10,60,100])
y = np.array([72,79,85,90,150,-135,120,-10,60,100.000001])

print("Comparaison sans tolérance")
print(np.equal(x,y))
print("Comparaison avec tolérance")
print(np.allclose(x,y))

Comparaison sans tolérance
[ True  True  True  True  True  True  True  True  True False]
Comparaison avec tolérance
True


In [39]:
#12
X = np.array([1,7,13,105])
print(X)
print("Place de mémoire utilisé par l'array")
print("%d bytes" % (X.size * X.itemsize))

[  1   7  13 105]
Place de mémoire utilisé par l'array
32 bytes


In [46]:
#13
a = np.zeros(10)
print(a)
a = np.ones(10)
print(a)
a = np.ones(10)*5
print(a)
a = np.full(10,7) #il y a dix 7 dans l'array
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[7 7 7 7 7 7 7 7 7 7]


In [52]:
#14
a = np.arange(start=30,stop=71,step=1)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [53]:
#15
a = np.arange(start=30,stop=71,step=2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [56]:
#16
a = np.identity(3, dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [83]:
#17

b = np.random.normal(0,1,1)
print(b)

[0.04168764]


In [70]:
#18

a = np.empty(15)

for i in range(15):
    a[i] = np.random.random()
    

print(a)
    
#on peut aussi initialiser une liste avec des valeurs random puis la transformer en array

[0.47022452 0.45772101 0.94350782 0.04308692 0.78363363 0.93350023
 0.17896089 0.40971868 0.80171294 0.1763002  0.2349272  0.6701654
 0.0864838  0.99890096 0.86133372]


In [85]:
#18

b = np.random.normal(0,1,15)
print(b)

[ 0.42967547 -0.22633481  0.01606093 -1.32212334  0.08576813 -0.4895398
  1.34175035 -0.57859899  1.2912439   0.01812506  1.46013413 -1.20368163
 -2.23123247 -0.92517971  3.1455118 ]


In [72]:
#19
print(np.array(list(np.random.randint(15,55) for i in range(10)))[1:-1])


[31 18 27 29 48 50 53 31]


In [86]:
v = np.arange(15,55)
print(v)
print(v[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [89]:
#20 à l'aide de la méthode reshape

a = np.arange(10,22).reshape((3,4))
print(a)

for x in np.nditer(a):
    print(x,end=" ")


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [81]:
#21
print(np.array(list(np.random.uniform(5,55) for i in range(2))))

[[17.37086182 11.57965526 43.55219756 11.90586076 30.86448475 41.80919239
  17.38002453 34.86906928 12.73191481 22.67894736]
 [ 8.58932438 38.27585254 34.89187953 28.64993805 18.26279792 39.78127956
  30.88952154 26.1230226  12.6811167  44.61147342]]


In [93]:
#21

v = np.linspace(5,50,10) #uniformisation des valeur print en fonction du nbr de valeur(ici 10)
print(v)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [82]:
#22
print(np.array(list( -i if 9<=i<=15 else i for i in range(20) )))

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [94]:
#22
x = np.arange(21)
print(v)
x[(x>9) & (x<= 15)] *= -1
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [96]:
#23
x = np.random.randint(0,11,5)
print(x)


[6 0 4 8 7]


In [97]:
#24
x = np.array([1,8,3,5])
print(x)
y = np.random.randint(0,11,4)
print(y)
result = x * y
print(result)


[1 8 3 5]
[4 6 1 1]
[ 4 48  3  5]


In [98]:
#25
ex = np.array ([0,1,2,3,4,5,6,7,8,9])
ex[ex%2 == 1] = -1
print(ex)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [100]:
#26
ex = np.array([0,1,2,3,4,5,6,7,8])
print("Méthode 1; \n",ex.reshape(3,-1))
print("Méthode 2; \n",ex.reshape(3,3))

Méthode 1; 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Méthode 2; 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [102]:
#27
ex = np.arange(4).reshape(2,-1)
print(ex)
print("Méthode 1; \n",ex + np.full((2,2),202))
print("Méthode 2; \n",ex + 202*np.ones((2,2)))

[[0 1]
 [2 3]]
Méthode 1; 
 [[202 203]
 [204 205]]
Méthode 2; 
 [[202. 203.]
 [204. 205.]]


In [103]:
#28
ex = np.random.randint(30,41, size = 10)
print(ex)

[40 34 33 37 30 36 39 33 36 34]


In [104]:
#29
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x>y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [105]:
#30
ex = np.arange(100).reshape(5,-1)
print(ex)

print("The extracted array:")
print(ex[:,:4]) #toutes les lignes, de la 1 à la 4ème colonne

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
The extracted array:
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
